# -*- coding: utf-8 -*-
"""
Created on Fri Apr  7 22:20:21 2023

@author: priya
"""
import random

def guessTheNumberGame(random):
    number = int(input("enter the number you think is generated by computer between 1 and 101"))
    print("random: ",random)
    while number!= random:
        if number < random:
            print("random number is higher than",number)
        else:
            print("random number is lower than ",number)
        number = int(input("try entering the number again"))
    return "You guess is correct! Congratulations!"

random = random.randint(1,101)
print(guessTheNumberGame(random))    

